nelmio_api_doc:
    documentation:
        servers:
          - url: localhost
            description: API over HTTP
        info:
            title: La Guilde des Seigneurs
            description: API utilis√©e pour La Guilde des Seigneurs
            version: "0.13.1"
    areas: # to filter documented areas
        path_patterns:
            - ^/((?!api|_error).*$) # Toutes les routes qui ne commencent pas par api ou error
